import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/component/NextAuthProvider";
import ReactQuery from "@/component/ReactQuery";
import { Session } from "next-auth";
import { ReactNode } from "react";

interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}
const inter = Inter({ subsets: ["latin"] });

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en" data-theme="">
      <body className={""}>
        <NextAuthProvider session={session}>
          <ReactQuery>
            {children}
          </ReactQuery>
        </NextAuthProvider>
      </body>
    </html>
  );
}
